ignite:
  client-mode: false # Operate in server mode
  ignite-instance-name: igniteInstance
  peer-class-loading-enabled: true
  dataStorageConfiguration:
    defaultDataRegionConfiguration:
      initialSize: 10485760 #10MB
    dataRegionConfigurations:
      - name: my-dataregion
        initialSize: 104857600 #100MB
  caches:
    cache1:
      cache-mode: PARTITIONED
      atomicity-mode: ATOMIC
      backups: 1
    cache2:
      cache-mode: PARTITIONED
      atomicity-mode: ATOMIC
      backups: 2